# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER hcp

# 挂载目录
VOLUME /home/hcp
# 创建目录
RUN mkdir -p /home/hcp
# 指定路径
WORKDIR /home/hcp
# 复制jar文件到路径
COPY ./jar/hcp-job.jar /home/hcp/vctgo-job.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","hcp-job.jar"]
