# 基础镜像
FROM nginx
# author
MAINTAINER hcp

# 挂载目录
VOLUME /home/hcp/projects/hcp-ui
# 创建目录
RUN mkdir -p /home/hcp/projects/hcp-ui
# 指定路径
WORKDIR /home/hcp/projects/hcp-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/hcp/projects/hcp-ui
